apiVersion: v1
kind: ConfigMap
metadata:
  name: stayhub-config
  namespace: stayhub
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  # Service discovery (internal K8s DNS)
  IdentityService__BaseUrl: "http://identity-api:8080"
  HotelService__BaseUrl: "http://hotel-api:8080"
  BookingService__BaseUrl: "http://booking-api:8080"
  PaymentService__BaseUrl: "http://payment-api:8080"
  ReviewService__BaseUrl: "http://review-api:8080"
  NotificationService__BaseUrl: "http://notification-api:8080"
  AnalyticsService__BaseUrl: "http://analytics-api:8080"
  # RabbitMQ
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
