// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayHub.Services.Booking.Infrastructure.Persistence;

#nullable disable

namespace StayHub.Services.Booking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayHub.Services.Booking.Domain.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GuestUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("RefundPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Bookings_ConfirmationNumber");

                    b.HasIndex("GuestUserId")
                        .HasDatabaseName("IX_Bookings_GuestUserId");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_Bookings_HotelId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BookingEntity_NotDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Bookings_Status");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("IX_Bookings_RoomId_Status");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("StayHub.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_CreatedAtUtc");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_Unprocessed")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("StayHub.Services.Booking.Domain.Entities.BookingEntity", b =>
                {
                    b.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "RefundAmount", b1 =>
                        {
                            b1.Property<Guid>("BookingEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Refund_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Refund_Currency");

                            b1.HasKey("BookingEntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingEntityId");
                        });

                    b.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.GuestInfo", "GuestInfo", b1 =>
                        {
                            b1.Property<Guid>("BookingEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Guest_Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Guest_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Guest_LastName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Guest_Phone");

                            b1.HasKey("BookingEntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingEntityId");
                        });

                    b.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.PriceBreakdown", "PriceBreakdown", b1 =>
                        {
                            b1.Property<Guid>("BookingEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Nights")
                                .HasColumnType("int")
                                .HasColumnName("Price_Nights");

                            b1.HasKey("BookingEntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingEntityId");

                            b1.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "NightlyRate", b2 =>
                                {
                                    b2.Property<Guid>("PriceBreakdownBookingEntityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("NightlyRate_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("NightlyRate_Currency");

                                    b2.HasKey("PriceBreakdownBookingEntityId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceBreakdownBookingEntityId");
                                });

                            b1.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "ServiceFee", b2 =>
                                {
                                    b2.Property<Guid>("PriceBreakdownBookingEntityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ServiceFee_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("ServiceFee_Currency");

                                    b2.HasKey("PriceBreakdownBookingEntityId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceBreakdownBookingEntityId");
                                });

                            b1.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "Subtotal", b2 =>
                                {
                                    b2.Property<Guid>("PriceBreakdownBookingEntityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Subtotal_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Subtotal_Currency");

                                    b2.HasKey("PriceBreakdownBookingEntityId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceBreakdownBookingEntityId");
                                });

                            b1.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "TaxAmount", b2 =>
                                {
                                    b2.Property<Guid>("PriceBreakdownBookingEntityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Tax_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Tax_Currency");

                                    b2.HasKey("PriceBreakdownBookingEntityId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceBreakdownBookingEntityId");
                                });

                            b1.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.Money", "Total", b2 =>
                                {
                                    b2.Property<Guid>("PriceBreakdownBookingEntityId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Total_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Total_Currency");

                                    b2.HasKey("PriceBreakdownBookingEntityId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceBreakdownBookingEntityId");
                                });

                            b1.Navigation("NightlyRate")
                                .IsRequired();

                            b1.Navigation("ServiceFee")
                                .IsRequired();

                            b1.Navigation("Subtotal")
                                .IsRequired();

                            b1.Navigation("TaxAmount")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.OwnsOne("StayHub.Services.Booking.Domain.ValueObjects.StayPeriod", "StayPeriod", b1 =>
                        {
                            b1.Property<Guid>("BookingEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("date")
                                .HasColumnName("CheckIn");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("date")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingEntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingEntityId");
                        });

                    b.Navigation("GuestInfo")
                        .IsRequired();

                    b.Navigation("PriceBreakdown")
                        .IsRequired();

                    b.Navigation("RefundAmount");

                    b.Navigation("StayPeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
