namespace StayHub.Services.Identity.Application.IntegrationEvents;

/// <summary>
/// Abstraction for sending email verification messages.
/// In the Application layer as a port — implemented by Infrastructure.
///
/// Current implementation: logs the verification link (development).
/// Future implementation: publishes to RabbitMQ via MassTransit
/// for the Notification Service to send the actual email.
/// </summary>
public interface IEmailVerificationSender
{
    /// <summary>
    /// Sends (or queues) a verification email to the user.
    /// </summary>
    /// <param name="userId">The user's ID.</param>
    /// <param name="email">The user's email address.</param>
    /// <param name="firstName">The user's first name (for personalization).</param>
    /// <param name="confirmationToken">The email confirmation token generated by ASP.NET Core Identity.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task SendVerificationEmailAsync(
        string userId,
        string email,
        string firstName,
        string confirmationToken,
        CancellationToken cancellationToken = default);
}
