using Microsoft.Extensions.Logging;
using StayHub.Services.Identity.Application.Abstractions;
using StayHub.Shared.CQRS;
using StayHub.Shared.Result;

namespace StayHub.Services.Identity.Application.Features.ResetPassword;

/// <summary>
/// Handles ResetPasswordCommand by delegating to IIdentityService.ResetPasswordAsync.
/// Uses the token generated by ForgotPasswordCommand to verify the reset request.
/// </summary>
internal sealed class ResetPasswordCommandHandler(
    IIdentityService identityService,
    ILogger<ResetPasswordCommandHandler> logger)
    : ICommandHandler<ResetPasswordCommand>
{
    public async Task<Result> Handle(
        ResetPasswordCommand request,
        CancellationToken cancellationToken)
    {
        var result = await identityService.ResetPasswordAsync(
            request.Email,
            request.Token,
            request.NewPassword,
            cancellationToken);

        if (result.IsFailure)
        {
            logger.LogWarning(
                "Password reset failed for {Email}: {Error}",
                request.Email,
                result.Error.Code);
        }
        else
        {
            logger.LogInformation("Password reset successfully for {Email}", request.Email);
        }

        return result;
    }
}
